#![allow(dead_code, unused_imports)]

//! Golden parity for the plugin-manager sidebar TUI against Python.
//!
//! The fixture is generated by importing `bridge.cmux_herdr_sidebar` and
//! calling its pure parser, renderer, ANSI, wrapping, and environment helpers.

#[path = "../src/model.rs"]
mod model;
#[path = "../src/sidebar.rs"]
mod sidebar;
#[path = "../src/status.rs"]
mod status;

use std::collections::HashMap;

use serde_json::Value;

fn golden() -> Value {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/sidebar_golden.json"
    ))
    .expect("read sidebar_golden.json");
    serde_json::from_str(&text).expect("parse golden")
}

#[test]
fn workspace_rows_match_python() {
    for case in golden()["workspaces"].as_array().unwrap() {
        let got: Vec<Value> = sidebar::workspaces_from_tree(&case["input"])
            .iter()
            .map(sidebar::WorkspaceRow::to_value)
            .collect();
        assert_eq!(Value::Array(got), case["output"], "case {}", case["name"]);
    }
}

#[test]
fn rendered_frames_match_python_byte_for_byte() {
    for case in golden()["renders"].as_array().unwrap() {
        let rows = sidebar::workspaces_from_tree(&case["tree"]);
        let got = sidebar::render_sidebar(
            &rows,
            case["selected"].as_i64().unwrap(),
            case["cols"].as_i64().unwrap(),
            case["rows_h"].as_i64().unwrap(),
            case["connected"].as_bool().unwrap(),
            case["message"].as_str().unwrap(),
        );
        assert_eq!(
            got,
            case["output"].as_str().unwrap(),
            "case {}",
            case["name"]
        );
    }
}

#[test]
fn text_helpers_match_python() {
    let g = golden();
    for case in g["helpers"]["clip"].as_array().unwrap() {
        assert_eq!(
            sidebar::clip(
                case["text"].as_str().unwrap(),
                case["width"].as_i64().unwrap()
            ),
            case["output"].as_str().unwrap()
        );
    }
    for case in g["helpers"]["wrap"].as_array().unwrap() {
        assert_eq!(
            serde_json::json!(sidebar::wrap(
                case["text"].as_str().unwrap(),
                case["width"].as_i64().unwrap()
            )),
            case["output"]
        );
    }
    for case in g["helpers"]["strip_ansi"].as_array().unwrap() {
        assert_eq!(
            sidebar::strip_ansi(case["text"].as_str().unwrap()),
            case["output"].as_str().unwrap()
        );
    }
}

#[test]
fn socket_environment_precedence_matches_python() {
    for case in golden()["socket_paths"].as_array().unwrap() {
        let env: HashMap<String, String> = case["input"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(key, value)| (key.clone(), value.as_str().unwrap().to_string()))
            .collect();
        assert_eq!(
            serde_json::json!(sidebar::socket_path_from_env(&env)),
            case["output"]
        );
    }
}
